sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: alchemy-graphl_dummy_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  <% if ENV['CI'] %>
  username: alchemy_user
  password: password
  <% end %>
  database: alchemy-graphl_dummy_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
