- name: header
  contents:
    - name: greeting
      type: EssenceText
    - name: hero_image
      type: EssencePicture

- name: article
  contents:
    - name: headline
      type: EssenceText
    - name: text
      type: EssenceRichtext
